In [58]:
#Bütikofer Kevin, Charles-Lewis Jaggi

import numpy as np
import matplotlib.pyplot as plt 

In [59]:
textfile = open('ex2-system-a.csv')
data = []
for line in textfile:
    row_data = line.strip("\n").split(";")[0:-1]
    for i, item in enumerate(row_data):
        try:
            row_data[i] = float(item)
        except ValueError:
            pass
    data.append(row_data)
data = np.array(data)

In [60]:
print(data)

[[5.34845e-08 7.49348e-10 8.08347e-07 ... 4.80859e-07 1.25033e-05
  7.00000e+00]
 [1.33427e-03 3.20296e-05 8.50428e-01 ... 1.45633e-03 1.06292e-05
  2.00000e+00]
 [3.64305e-06 9.96276e-01 2.04591e-03 ... 5.15012e-04 4.42546e-05
  1.00000e+00]
 ...
 [3.85164e-07 5.58216e-06 6.71923e-07 ... 4.83738e-03 1.70994e-02
  4.00000e+00]
 [5.83727e-05 4.88072e-05 6.84844e-09 ... 2.75059e-03 9.24820e-07
  5.00000e+00]
 [1.36955e-06 4.46433e-10 2.76675e-05 ... 9.84101e-09 4.13793e-09
  6.00000e+00]]


In [65]:
y_pred = []
def compute(data):
    for row in data:
        y_pred.append(np.argmax(row[0:-1]))

compute(data)
error = 1 - np.sum(y_pred == data[:,-1]) / len(data)
print("error : ", error)

error :  0.10729999999999995


In [96]:
matrix = np.zeros([10,10])
matrix = matrix.astype(int)
yt = data[:,-1]
print(matrix)

for yp, y in zip(y_pred, yt):
        matrix[yp, int(y)] += 1
    


[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [97]:

print(matrix)

[[ 944    0   10    1    2   12   14    0   12   10]
 [   0 1112    6    1    3    3    3   14   16    4]
 [  11    2  921   31    6    6   21   30   18    6]
 [   0    3   12  862    2   29    2    9   26   22]
 [   0    1   15    2  910   19   22    7   24   53]
 [   2    4    3   72    1  768   28    2   46   18]
 [  10    3   19    5   12   19  865    1   22    0]
 [   7    1   15   14    6    9    0  929   19   48]
 [   5    9   26   12    4   21    3    3  772    4]
 [   1    0    5   10   36    6    0   33   19  844]]
