In [1]:
#Bütikofer Kevin, Charles-Lewis Jaggi

import numpy as np
import matplotlib.pyplot as plt 

In [2]:
def openFile(fileName):
    textfile = open(fileName)
    data = []
    for line in textfile:
        row_data = line.strip("\n").split(";")[0:-1]
        for i, item in enumerate(row_data):
            try:
                row_data[i] = float(item)
            except ValueError:
                pass
        data.append(row_data)
    return np.array(data)



## a)

In [4]:
y_pred = []
def compute(data):
    for row in data:
        y_pred.append(np.argmax(row[0:-1]))



## b), c)

In [6]:
def computeMatrix(data):
    matrix = np.zeros([10,10])
    matrix = matrix.astype(int)
    yt = data[:,-1]

    for yp, y in zip(y_pred, yt):
            matrix[int(y), yp] += 1

    precisions = []
    recalls = []
    f1s = []
    for i in range(10):
        precisions.append(matrix[i,i]/np.sum(matrix[:,i]))
        recalls.append(matrix[i,i]/np.sum(matrix[i,:]))
        f1s.append((precisions[-1]*recalls[-1])/precisions[-1]+recalls[-1])

    print(matrix)
    
    print("Best precision class index : ", np.argmax(precisions))
    print("Best recall class index : ", np.argmax(recalls))
    print("Worst precision class index : ", np.argmin(precisions))
    print("Worst recall class index : ", np.argmin(recalls))
    print("Best f1 score class index : ", np.argmax(recalls), " with f1 = ", max(f1s))
    print("Worst f1 score class index : ", np.argmin(recalls), " with f1 = ", min(f1s))

In [7]:
data = openFile('ex2-system-a.csv')
y_pred = []
compute(data)
error = 1 - np.sum(y_pred == data[:,-1]) / len(data)
print("error : ", error)
computeMatrix(data)

error :  0.10729999999999995
[[ 944    0   11    0    0    2   10    7    5    1]
 [   0 1112    2    3    1    4    3    1    9    0]
 [  10    6  921   12   15    3   19   15   26    5]
 [   1    1   31  862    2   72    5   14   12   10]
 [   2    3    6    2  910    1   12    6    4   36]
 [  12    3    6   29   19  768   19    9   21    6]
 [  14    3   21    2   22   28  865    0    3    0]
 [   0   14   30    9    7    2    1  929    3   33]
 [  12   16   18   26   24   46   22   19  772   19]
 [  10    4    6   22   53   18    0   48    4  844]]
Best precision class index :  1
Best recall class index :  1
Worst precision class index :  5
Worst recall class index :  8
Best f1 score class index :  1  with f1 =  1.9594713656387666
Worst f1 score class index :  8  with f1 =  1.5852156057494866


In [8]:
data = openFile('ex2-system-b.csv')
y_pred = []
compute(data)
error = 1 - np.sum(y_pred == data[:,-1]) / len(data)
print("error : ", error)
computeMatrix(data)

error :  0.03869999999999996
[[ 963    0    4    1    0    2    6    2    2    0]
 [   0 1123    3    1    0    0    5    1    2    0]
 [   5    0  996    7    4    0    4    8    6    2]
 [   0    0   13  985    0    3    1    3    3    2]
 [   1    2    4    0  938    1    9    2    5   20]
 [   8    1    0   27    1  830   12    1    8    4]
 [   6    3    2    1    7    4  930    1    4    0]
 [   0    7   18   10    3    1    0  981    0    8]
 [   7    1    7   19    5    7    4    7  912    5]
 [   3    4    1   14   11    6    2    8    5  955]]
Best precision class index :  1
Best recall class index :  1
Worst precision class index :  3
Worst recall class index :  5
Best f1 score class index :  1  with f1 =  1.9788546255506607
Worst f1 score class index :  5  with f1 =  1.8609865470852018


The second dataset is better for errorrate and f1 score